### ISSUE TITLE
Error: refusing to allow an OAuth App to create or update workflow

### ISSUE THREAD

**Issue by itsdfish** [StatisticalRethinkingJulia/MCMCBenchmarkSuite.jl#2]
Hi @goedman -

I am trying to add the automated package updating that you added to MCMCBenchmarks, but I run into this error. Do you know what I need to do in order to fix it? Thanks!

```
To https://github.com/itsdfish/MCMCBenchmarkSuite
 ! [remote rejected] master -> master (refusing to allow an OAuth App to create or update workflow `.github/workflows/CompatHelper.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/itsdfish/MCMCBenchmarkSuite'

```

**Comment by goedman** [comment]
Not 100% sure. Were you trying to add CompatHelper and TagBot by committing to a repo?

Just added these two using the Actions button on Github, but was that your question/issue?

**Comment by goedman** [comment]
Also enabled Travis testing on the repo. I am a bit concerned about the repo name, shouldn't it be MCMCBenchmarkSuite.jl (or MCMCBenchmarkSuite.jl.git)?

**Comment by goedman** [comment]
The PRs (pull requests) by CompatHelper are a bit tricky, at least on my system. I tend to indeed merge them in the correct sequence (otherwise I have seen merge conflicts arise) and then after confirming the merge I delete the branch (all on Github).

**Comment by itsdfish** [comment]
Thanks Rob. I guess I am learning a few things still. I will add those to the action list in the future.

I didn't realize that .jl was appended to the repo names. I think I can change that without too much trouble since the repo is not registered.
